// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/17/2024, 1:21:16 PM
const configMerger = require("/Users/kevintjhia/Documents/projects/work/boilerplate-nuxt3/boilerplate-frontend/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/kevintjhia/Documents/projects/work/boilerplate-nuxt3/boilerplate-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevintjhia/Documents/projects/work/boilerplate-nuxt3/boilerplate-frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevintjhia/Documents/projects/work/boilerplate-nuxt3/boilerplate-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevintjhia/Documents/projects/work/boilerplate-nuxt3/boilerplate-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevintjhia/Documents/projects/work/boilerplate-nuxt3/boilerplate-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevintjhia/Documents/projects/work/boilerplate-nuxt3/boilerplate-frontend/plugins/**/*.{js,ts,mjs}","/Users/kevintjhia/Documents/projects/work/boilerplate-nuxt3/boilerplate-frontend/composables/**/*.{js,ts,mjs}","/Users/kevintjhia/Documents/projects/work/boilerplate-nuxt3/boilerplate-frontend/utils/**/*.{js,ts,mjs}","/Users/kevintjhia/Documents/projects/work/boilerplate-nuxt3/boilerplate-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kevintjhia/Documents/projects/work/boilerplate-nuxt3/boilerplate-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kevintjhia/Documents/projects/work/boilerplate-nuxt3/boilerplate-frontend/app.config.{js,ts,mjs}"] }));

module.exports = config
